# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f99606ce5c859082506d03474e9d6f0250b1bc0c182b7a6e813563490efe933d3ab4d9a795cdac79882a233ca438e6122ee09269f0c60db6aaf64da3a280cc92

test:
  secret_key_base: 0a79c6daf84674666ea4c70d54c0ca73fc61d90e81536d410a3210985c89b8c8b1ef86e805c6f105f53a293f5d1a7178ff342fe3107c6a1490fb01d891ce4d0e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
